// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtkezswjqiunrzeppywd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0a2V6c3dqcWl1bnJ6ZXBweXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1Mzc3MjAsImV4cCI6MjA3MjExMzcyMH0.tCljBH1Hp1yzwCBC76OctIhef7ZSeltrAE2dXOB_n-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});